SELECT
    i.FOOD_TYPE,
    i.REST_ID,
    i.REST_NAME,
    i.FAVORITES
FROM REST_INFO i
JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAV
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) m
ON i.FOOD_TYPE = m.FOOD_TYPE
AND i.FAVORITES = m.MAX_FAV
ORDER BY FOOD_TYPE DESC;

# 음식 종류별 최대 즐겨찾기만 구하는 테이블을 만든다