SELECT
    ID,
    CASE
        WHEN QUAT = 1 THEN 'CRITICAL'
        WHEN QUAT = 2 THEN 'HIGH'
        WHEN QUAT = 3 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM (
    SELECT
        ID,
        NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS QUAT
    FROM ECOLI_DATA
) AS CLASS
ORDER BY ID;