SELECT H.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '세단'
) AS C ON H.CAR_ID = C.CAR_ID
WHERE H.START_DATE BETWEEN '2022-10-01' AND '2022-10-31'
GROUP BY H.CAR_ID
ORDER BY H.CAR_ID DESC
